"""Add item in Order Table

Revision ID: 97580488d8e6
Revises: 7e5f7aa7b05f
Create Date: 2026-03-09 19:32:07.045027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97580488d8e6'
down_revision: Union[str, Sequence[str], None] = '7e5f7aa7b05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('unit_price', sa.Float(), nullable=True))
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.FLOAT(), nullable=True))
    op.drop_column('order_items', 'unit_price')
    # ### end Alembic commands ###
